#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run lint-staged to check and fix files
npx lint-staged

# Run type check
yarn type-check

# Run tests (optional - can be removed if too slow)
yarn test --passWithNoTests
