name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run linter with strict checks
        run: yarn lint:check

      - name: Run type check
        run: yarn type-check

      - name: Run tests with coverage
        run: yarn test:ci

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: test-results/junit.xml

      - name: Build application
        run: yarn build

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        if: always()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          files: ./coverage/lcov.info,./coverage/coverage-final.json
          flags: unittests
          name: sudoku-solver-coverage
          fail_ci_if_error: false
          verbose: true
